#!/bin/bash

# Options
icon_url='https://wiki.ubuntu.com/IceWeaselIcon?action=AttachFile&do=get&target=IYY_new_tangoish.png'
icon_dir='/usr/share/iceweasel/chrome/icons/default'
pixmap_dir='/usr/share/pixmaps'

# get the new icon
curl -o iw_new.png -O $icon_url

# do the magick
for size in 16 32 48; do
    convert iw_new.png -resize ${size}x$size iw_${size}.png
    cp -v $icon_dir/default${size}.png $icon_dir/default${size}.png.orig
    mv -v iw_${size}.png $icon_dir/default${size}.png 
done

# one xpm file left
convert iw_new.png -resize 32x32 iw_32.xpm
cp -v $pixmap_dir/iceweasel.xpm $pixmap_dir/iceweasel.png.orig
mv -v iw_32.xpm $pixmap_dir/iceweasel.xpm

# remove the downloaded file
rm iw_new.png

echo
echo "$0 is finished."
